# Generated by Django 5.2.1 on 2025-05-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(max_length=20)),
                ('servico', models.CharField(default='Corte de Cabelo', max_length=100)),
                ('data_agendamento', models.DateField()),
                ('hora_agendamento', models.TimeField()),
                ('status', models.CharField(default='pendente', max_length=50)),
            ],
            options={
                'verbose_name': 'Agendamento da Barbearia',
                'verbose_name_plural': 'Agendamentos da Barbearia',
                'ordering': ['data_agendamento', 'hora_agendamento'],
            },
        ),
    ]
